import {
  BakeryCategory,
  BakeryItem,
  DeliveryArea,
  MenuCategory,
  MenuPrepStation,
  MenuItem,
  ModifierGroup,
  OptionGroupRegistryEntry,
  RestaurantSettings,
  StationType,
} from '../types';

export interface SeedMenuItem extends Omit<MenuItem, 'categoryId'> {
  categoryKey: string;
}

export interface SeedBakeryItem extends Omit<BakeryItem, 'bakeryCategoryName'> {}

const ACCOMPANIMENT_OPTIONS = [
  'Posho / Ugali',
  'Plain Rice',
  'Pilau Rice',
  'Spaghetti',
  'Boiled Potatoes',
  'Boiled Bananas',
  'French Fries',
  'Lyonaise Potatoes',
  'Fresh Beans',
  'Mixed Vegetables',
  'Greens',
];

const PIZZA_TOPPING_OPTIONS = [
  'Mushroom',
  'Spinach',
  'Green Pepper',
  'Pineapple',
  'Onions',
  'Roasted Red Pepper',
];

function buildSingleChoiceGroup(id: string, name: string, options: Array<{ id: string; name: string; priceDelta?: number; prepStation?: MenuPrepStation }>): ModifierGroup {
  return {
    id,
    name,
    selectionType: 'single',
    required: true,
    minSelections: 1,
    maxSelections: 1,
    options: options.map((option) => ({
      ...option,
      priceDelta: option.priceDelta || 0,
      active: true,
      prepStation: option.prepStation,
      station: option.prepStation === 'barista' ? 'barista' : option.prepStation === 'kitchen' ? 'kitchen' : undefined,
    })),
  };
}

function toModifierGroup(entry: OptionGroupRegistryEntry): ModifierGroup {
  const isAccompanimentPair = entry.id === 'accompaniments_2';
  return {
    id: entry.id,
    name: entry.name,
    selectionType: entry.multiSelect ? 'multiple' : 'single',
    required: entry.required,
    minSelections: isAccompanimentPair ? 2 : entry.required ? 1 : undefined,
    maxSelections: isAccompanimentPair ? 2 : entry.multiSelect ? undefined : 1,
    options: entry.options.map((option) => ({
      id: option.id,
      name: option.name,
      priceDelta: option.priceDelta,
      active: true,
      prepStation: option.prepStation,
      station: option.prepStation === 'barista' ? 'barista' : option.prepStation === 'kitchen' ? 'kitchen' : undefined,
    })),
  };
}

function getModifierGroupsByIds(ids: string[]): ModifierGroup[] {
  return ids
    .map((id) => optionGroupsRegistry[id])
    .filter((entry): entry is OptionGroupRegistryEntry => !!entry)
    .map((entry) => toModifierGroup(entry));
}

export const optionGroupsRegistry: Record<string, OptionGroupRegistryEntry> = {
  protein_selection: {
    id: 'protein_selection',
    name: 'Choose your protein',
    required: true,
    multiSelect: false,
    options: [
      { id: 'beef', name: 'Beef', priceDelta: 0 },
      { id: 'chicken', name: 'Chicken', priceDelta: 0 },
      { id: 'fish', name: 'Fish', priceDelta: 0 },
      { id: 'vegetable', name: 'Vegetable', priceDelta: 0 },
    ],
  },
  accompaniments_2: {
    id: 'accompaniments_2',
    name: 'Choose any 2 accompaniments',
    required: true,
    multiSelect: true,
    options: ACCOMPANIMENT_OPTIONS.map((name) => ({
      id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
      name,
      priceDelta: 0,
    })),
  },
  breakfast_drink_choice: {
    id: 'breakfast_drink_choice',
    name: 'Choose your drink',
    required: true,
    multiSelect: false,
    options: [
      { id: 'african-tea', name: 'African Tea', priceDelta: 0, prepStation: 'barista' },
      { id: 'black-coffee', name: 'Black Coffee', priceDelta: 0, prepStation: 'barista' },
    ],
  },
  omelette_style: {
    id: 'omelette_style',
    name: 'Choose omelette style',
    required: true,
    multiSelect: false,
    options: [
      { id: 'spanish-omelette', name: 'Spanish Omelette', priceDelta: 0, prepStation: 'kitchen' },
      { id: 'english-omelette', name: 'English Omelette', priceDelta: 0, prepStation: 'kitchen' },
    ],
  },
  pizza_crust: {
    id: 'pizza_crust',
    name: 'Choose your crust',
    required: true,
    multiSelect: false,
    options: [
      { id: 'thin-crust', name: 'Thin Crust', priceDelta: 0 },
      { id: 'classic-crust', name: 'Classic Crust', priceDelta: 0 },
    ],
  },
  pizza_sauce: {
    id: 'pizza_sauce',
    name: 'Choose your sauce',
    required: true,
    multiSelect: false,
    options: [
      { id: 'tomato-sauce', name: 'Tomato Sauce', priceDelta: 0 },
      { id: 'bbq-sauce', name: 'BBQ Sauce', priceDelta: 0 },
    ],
  },
  pizza_cheese: {
    id: 'pizza_cheese',
    name: 'Choose your cheese level',
    required: true,
    multiSelect: false,
    options: [
      { id: 'regular-cheese', name: 'Regular Cheese', priceDelta: 0 },
      { id: 'extra-cheese', name: 'Extra Cheese', priceDelta: 1000 },
    ],
  },
  pizza_toppings: {
    id: 'pizza_toppings',
    name: 'Add toppings',
    required: false,
    multiSelect: true,
    options: PIZZA_TOPPING_OPTIONS.map((name) => ({
      id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
      name,
      priceDelta: 1000,
    })),
  },
};

export const SEED_CATEGORIES: MenuCategory[] = [
  { id: 'signature-meals', name: 'Signature Meals', slug: 'signature-meals', active: true, iconName: 'Utensils', sortOrder: 1, station: 'kitchen', categoryGroup: 'main' },
  { id: 'breakfast', name: 'Breakfast', slug: 'breakfast', active: true, iconName: 'Coffee', sortOrder: 2, station: 'kitchen', categoryGroup: 'main' },
  { id: 'pizza', name: 'Pizza', slug: 'pizza', active: true, iconName: 'Pizza', sortOrder: 3, station: 'kitchen', categoryGroup: 'main' },
  { id: 'fresh-fruits', name: 'Fresh Fruits', slug: 'fresh-fruits', active: true, iconName: 'Cherry', sortOrder: 4, station: 'barista', categoryGroup: 'main' },
  { id: 'fresh-juice', name: 'Fresh Juice', slug: 'fresh-juice', active: true, iconName: 'Cherry', sortOrder: 5, station: 'barista', categoryGroup: 'main' },
  { id: 'coffee-espresso', name: 'Coffee & Espresso', slug: 'coffee-espresso', active: true, iconName: 'Coffee', sortOrder: 6, station: 'barista', categoryGroup: 'main' },
  { id: 'beverages', name: 'Beverages', slug: 'beverages', active: true, iconName: 'GlassWater', sortOrder: 7, station: 'barista', categoryGroup: 'main' },
  { id: 'cocktails-wines', name: 'Cocktails & Wines', slug: 'cocktails-wines', active: true, iconName: 'Wine', sortOrder: 8, station: 'barista', categoryGroup: 'main' },
];

export const SEED_SETTINGS: RestaurantSettings = {
  name: 'KUCI Café & Bakery',
  tagline: 'Cafe ordering for every craving',
  description: 'A mobile-first ordering experience for KUCI Cafe & Bakery in Nyamata.',
  active: true,
  contactInfo: {
    phone: '+250795306488',
    whatsapp: '+250783959404',
    email: 'hello@kuci.rw',
    location: 'Nyamata, Bugesera, Rwanda (Opposite AFOS Bugesera)',
    mapLink: "https://www.google.com/maps/place/2%C2%B008'46.6%22S+30%C2%B005'20.0%22E/@-2.146271,30.086319,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-2.146271!4d30.0888939?hl=en&entry=ttu",
    contactPerson: 'Lorraine Ingabire',
    momoPayCode: '6482249',
    momoMerchantName: 'KUCI HOLDINGS',
    hours: '7AM - 10PM',
  },
  colors: {
    primary: '#f97316',
    text: '#3e2723',
    bg: '#fffdfa',
    bgSecondary: '#f5f5dc',
  },
  extraCosts: {
    topping: 1000,
    otherExtra: 1000,
  },
  paymentMethods: ['momo', 'cash'],
  deliveryOptions: {
    [DeliveryArea.NYAMATA_CENTRAL]: {
      area: DeliveryArea.NYAMATA_CENTRAL,
      fee: 500,
      estimatedTime: '30-45 mins',
    },
    [DeliveryArea.WITHIN_5KM]: {
      area: DeliveryArea.WITHIN_5KM,
      fee: 1000,
      estimatedTime: '45-60 mins',
    },
    [DeliveryArea.OUTSIDE]: {
      area: DeliveryArea.OUTSIDE,
      fee: 0,
      estimatedTime: 'Contact us for timing',
    },
  },
  customizationOptions: {
    sides: ACCOMPANIMENT_OPTIONS,
    pizzaToppings: PIZZA_TOPPING_OPTIONS,
    breakfastToppings: ['Maple Syrup', 'Fresh Fruit', 'Whipped Cream', 'Honey', 'Chocolate Sauce'],
    burritoFillings: ['Extra Eggs', 'Extra Cheese', 'Extra Bacon', 'Double Salsa', 'Sausage', 'Avocado'],
  },
};

export const SEED_BAKERY_CATEGORIES: BakeryCategory[] = [
  {
    id: 'breads',
    name: 'Breads',
    slug: 'breads',
    iconName: 'BreadSlice',
    sortOrder: 1,
    active: true,
    description: 'Daily breads, buns, and specialty loaves.',
    serviceAreaDefault: 'bakery',
    frontLaneDefault: 'bakery_front',
    dispatchModeDefault: 'bakery_front_only',
  },
  {
    id: 'cakes',
    name: 'Cakes',
    slug: 'cakes',
    iconName: 'CakeSlice',
    sortOrder: 2,
    active: true,
    description: 'Whole cakes and cake slices for everyday and celebrations.',
    serviceAreaDefault: 'bakery',
    frontLaneDefault: 'bakery_front',
    dispatchModeDefault: 'bakery_front_only',
  },
  {
    id: 'pastries-snacks',
    name: 'Pastries & Snacks',
    slug: 'pastries-snacks',
    iconName: 'Croissant',
    sortOrder: 3,
    active: true,
    description: 'Croissants, samosas, mandazi, and savory bakes.',
    serviceAreaDefault: 'bakery',
    frontLaneDefault: 'bakery_front',
    dispatchModeDefault: 'bakery_front_only',
  },
  {
    id: 'breakfast-light-bites',
    name: 'Breakfast & Light Bites',
    slug: 'breakfast-light-bites',
    iconName: 'UtensilsCrossed',
    sortOrder: 4,
    active: true,
    description: 'Bakery-front morning bites served ready for handover.',
    serviceAreaDefault: 'bakery',
    frontLaneDefault: 'bakery_front',
    dispatchModeDefault: 'bakery_front_only',
  },
];

export const SEED_BAKERY_ITEMS: SeedBakeryItem[] = [
  {
    id: 'white-bread-loaf',
    name: 'WHITE BREAD LOAF',
    slug: 'white-bread-loaf',
    bakeryCategoryId: 'breads',
    price: 2500,
    description: 'Soft white sandwich loaf baked fresh daily.',
    imageUrl: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&q=80&w=800',
    active: true,
    sortOrder: 1,
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'bread',
    serviceArea: 'bakery',
    sku: 'BRD-WHITE-LOAF',
  },
  {
    id: 'brown-bread-loaf',
    name: 'BROWN BREAD LOAF',
    slug: 'brown-bread-loaf',
    bakeryCategoryId: 'breads',
    price: 3000,
    description: 'Whole grain brown loaf with hearty texture.',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
    active: true,
    sortOrder: 2,
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'bread',
    serviceArea: 'bakery',
    sku: 'BRD-BROWN-LOAF',
  },
  {
    id: 'milk-bread-loaf',
    name: 'MILK BREAD LOAF',
    slug: 'milk-bread-loaf',
    bakeryCategoryId: 'breads',
    price: 3200,
    description: 'Rich and fluffy milk bread loaf.',
    active: true,
    sortOrder: 3,
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'bread',
    serviceArea: 'bakery',
    sku: 'BRD-MILK-LOAF',
  },
  {
    id: 'burger-buns-pack',
    name: 'BURGER BUNS (PACK)',
    slug: 'burger-buns-pack',
    bakeryCategoryId: 'breads',
    price: 2000,
    description: 'Fresh burger buns, ideal for home burgers.',
    active: true,
    sortOrder: 4,
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'bread',
    serviceArea: 'bakery',
    sku: 'BRD-BUNS-PACK',
  },
  {
    id: 'banana-cake-slice-bakery',
    name: 'BANANA CAKE SLICE',
    slug: 'banana-cake-slice-bakery',
    bakeryCategoryId: 'cakes',
    price: 500,
    description: 'Moist banana cake slice.',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800',
    active: true,
    sortOrder: 1,
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'slice',
    serviceArea: 'bakery',
    sku: 'CAKE-BANANA-SLICE',
  },
  {
    id: 'chocolate-cake-slice',
    name: 'CHOCOLATE CAKE SLICE',
    slug: 'chocolate-cake-slice',
    bakeryCategoryId: 'cakes',
    price: 2500,
    description: 'Rich chocolate cake slice with soft sponge.',
    active: true,
    sortOrder: 2,
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'slice',
    serviceArea: 'bakery',
    sku: 'CAKE-CHOCO-SLICE',
  },
  {
    id: 'black-forest-whole-cake',
    name: 'BLACK FOREST WHOLE CAKE',
    slug: 'black-forest-whole-cake',
    bakeryCategoryId: 'cakes',
    price: 28000,
    description: 'Whole black forest cake for celebrations.',
    active: true,
    sortOrder: 3,
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'whole_cake',
    serviceArea: 'bakery',
    sku: 'CAKE-BLACKFOREST-WHOLE',
  },
  {
    id: 'butter-croissant',
    name: 'BUTTER CROISSANT',
    slug: 'butter-croissant',
    bakeryCategoryId: 'pastries-snacks',
    price: 2500,
    description: 'Flaky butter croissant.',
    active: true,
    sortOrder: 1,
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'pastry',
    serviceArea: 'bakery',
    sku: 'PSTRY-CROISSANT-BUTTER',
  },
  {
    id: 'mandazi',
    name: 'MANDAZI',
    slug: 'mandazi',
    bakeryCategoryId: 'pastries-snacks',
    price: 1000,
    description: 'Lightly sweet fried dough favorite.',
    active: true,
    sortOrder: 2,
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'pastry',
    serviceArea: 'bakery',
    sku: 'PSTRY-MANDAZI',
  },
  {
    id: 'vegetable-samosa',
    name: 'VEGETABLE SAMOSA',
    slug: 'vegetable-samosa',
    bakeryCategoryId: 'pastries-snacks',
    price: 1200,
    description: 'Crispy pastry filled with spiced vegetables.',
    active: true,
    sortOrder: 3,
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'pastry',
    serviceArea: 'bakery',
    sku: 'PSTRY-SAMOSA-VEG',
  },
  {
    id: 'sausage-roll',
    name: 'SAUSAGE ROLL',
    slug: 'sausage-roll',
    bakeryCategoryId: 'pastries-snacks',
    price: 2000,
    description: 'Golden baked pastry with sausage filling.',
    active: true,
    sortOrder: 4,
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'pastry',
    serviceArea: 'bakery',
    sku: 'PSTRY-SAUSAGE-ROLL',
  },
  {
    id: 'pancake',
    name: 'PANCAKE',
    slug: 'pancake',
    bakeryCategoryId: 'breakfast-light-bites',
    price: 4500,
    description: 'Golden pancake served as a bakery-front ready breakfast bite.',
    active: true,
    sortOrder: 1,
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'simple',
    serviceArea: 'bakery',
    sku: 'BRKFST-PANCAKE',
  },
  {
    id: 'chapati',
    name: 'CHAPATI',
    slug: 'chapati',
    bakeryCategoryId: 'breakfast-light-bites',
    price: 1200,
    description: 'Soft chapati sold and handed over directly at bakery front.',
    active: true,
    sortOrder: 2,
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'simple',
    serviceArea: 'bakery',
    sku: 'BRKFST-CHAPATI',
  },
];

export const SEED_MENU_ITEMS: SeedMenuItem[] = [
  {
    id: 'kuci-classic',
    name: 'KUCI CLASSIC',
    description: 'Fragrant rice dancing with aromatic spices, crowned with your choice of tender beef or succulent chicken.',
    category: 'Signature Meals',
    categoryKey: 'signature-meals',
    categoryName: 'Signature Meals',
    basePrice: 5000,
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=800',
    active: true,
    isAvailable: true,
    available: true,
    station: 'kitchen',
    prepStation: 'kitchen',
    fulfillmentMode: 'made_to_order',
    itemType: 'configurable',
    tagline: 'Our house legend on a plate',
    descriptionShort: 'Our house legend on a plate',
    featured: true,
    sortOrder: 1,
    tags: ['signature', 'rice'],
    optionGroupIds: ['protein_selection', 'accompaniments_2'],
    modifierGroups: getModifierGroupsByIds(['protein_selection', 'accompaniments_2']),
    reviews: [
      { user: 'Alice M.', rating: 5, comment: "Best rice I've had in Bugesera! The spices are just right.", date: '12/03/24' },
    ],
    averageRating: 4.8,
  },
  {
    id: 'chicken-stew',
    name: 'CHICKEN STEW',
    description: 'Boneless chicken pieces nestled in a rich peppery stew, served with your choice of accompaniments.',
    category: 'Signature Meals',
    categoryKey: 'signature-meals',
    categoryName: 'Signature Meals',
    basePrice: 5000,
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=800',
    active: true,
    isAvailable: true,
    available: true,
    station: 'kitchen',
    prepStation: 'kitchen',
    fulfillmentMode: 'made_to_order',
    itemType: 'configurable',
    tagline: 'Comfort in every spoonful',
    descriptionShort: 'Comfort in every spoonful',
    sortOrder: 2,
    tags: ['stew'],
    optionGroupIds: ['accompaniments_2'],
    modifierGroups: getModifierGroupsByIds(['accompaniments_2']),
  },
  {
    id: 'whole-fish',
    name: 'WHOLE FISH',
    description: 'Fresh whole fish grilled or fried, with portions priced by size.',
    category: 'Signature Meals',
    categoryKey: 'signature-meals',
    categoryName: 'Signature Meals',
    basePrice: 15000,
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&q=80&w=800',
    active: true,
    isAvailable: true,
    available: true,
    station: 'kitchen',
    prepStation: 'kitchen',
    fulfillmentMode: 'made_to_order',
    itemType: 'variant',
    tagline: 'Catch of the day, prepared your way',
    descriptionShort: 'Catch of the day, prepared your way',
    sortOrder: 3,
    tags: ['fish'],
    variants: [
      { id: 'whole-fish-small', name: 'Small', price: 15000, active: true, isDefault: true },
      { id: 'whole-fish-medium', name: 'Medium', price: 20000, active: true },
      { id: 'whole-fish-large', name: 'Large', price: 25000, active: true },
    ],
    modifierGroups: [
      buildSingleChoiceGroup('fish-preparation', 'Choose preparation', [
        { id: 'grilled', name: 'Grilled' },
        { id: 'fried', name: 'Fried' },
      ]),
    ],
  },
  {
    id: 'kuci-breakfast',
    name: 'KUCI BREAKFAST',
    description: 'Spanish or English omelette, fresh fruits, crispy chicken wing, vegetable potato cakes, and your choice of tea.',
    category: 'Breakfast',
    categoryKey: 'breakfast',
    categoryName: 'Breakfast',
    basePrice: 6000,
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=800',
    active: true,
    isAvailable: true,
    available: true,
    station: 'kitchen',
    prepStation: 'none',
    fulfillmentMode: 'made_to_order',
    itemType: 'composite',
    tagline: 'The Kuci signature morning',
    descriptionShort: 'The Kuci signature morning',
    featured: true,
    sortOrder: 1,
    tags: ['breakfast', 'composite'],
    optionGroupIds: ['omelette_style', 'breakfast_drink_choice'],
    modifierGroups: getModifierGroupsByIds(['omelette_style', 'breakfast_drink_choice']),
    components: [
      {
        id: 'omelette',
        name: 'Omelette',
        prepStation: 'kitchen',
        required: true,
        quantity: 1,
        optionGroupId: 'omelette_style',
      },
      {
        id: 'chicken-wing',
        name: 'Chicken Wing',
        prepStation: 'kitchen',
        required: true,
        quantity: 1,
      },
      {
        id: 'vegetable-potato-cakes',
        name: 'Vegetable Potato Cakes',
        prepStation: 'kitchen',
        required: true,
        quantity: 1,
      },
      {
        id: 'fruit',
        name: 'Fresh Fruits',
        prepStation: 'front',
        required: true,
        quantity: 1,
      },
      {
        id: 'drink',
        name: 'Breakfast Drink',
        prepStation: 'barista',
        required: true,
        quantity: 1,
        optionGroupId: 'breakfast_drink_choice',
      },
    ],
  },
  {
    id: 'omelette',
    name: 'OMELETTE',
    description: 'Freshly prepared omelette from the live kitchen line.',
    category: 'Breakfast',
    categoryKey: 'breakfast',
    categoryName: 'Breakfast',
    basePrice: 3500,
    active: true,
    isAvailable: true,
    available: true,
    station: 'kitchen',
    prepStation: 'kitchen',
    fulfillmentMode: 'made_to_order',
    itemType: 'configurable',
    descriptionShort: 'Kitchen-made omelette',
    sortOrder: 2,
    tags: ['breakfast', 'egg'],
    optionGroupIds: ['omelette_style'],
    modifierGroups: getModifierGroupsByIds(['omelette_style']),
  },
  {
    id: 'toast',
    name: 'TOAST',
    description: 'Fresh hot toast prepared to order in the kitchen.',
    category: 'Breakfast',
    categoryKey: 'breakfast',
    categoryName: 'Breakfast',
    basePrice: 2500,
    active: true,
    isAvailable: true,
    available: true,
    station: 'kitchen',
    prepStation: 'kitchen',
    fulfillmentMode: 'made_to_order',
    itemType: 'simple',
    descriptionShort: 'Kitchen toast made to order',
    sortOrder: 3,
    tags: ['breakfast', 'toast'],
  },
  {
    id: 'make-your-own-pizza',
    name: 'MAKE YOUR OWN PIZZA',
    description: 'Choose your base pizza and finish it with your own topping combination.',
    category: 'Pizza',
    categoryKey: 'pizza',
    categoryName: 'Pizza',
    basePrice: 10000,
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
    active: true,
    isAvailable: true,
    available: true,
    station: 'kitchen',
    prepStation: 'kitchen',
    fulfillmentMode: 'made_to_order',
    itemType: 'configurable',
    tagline: 'Be the chef',
    descriptionShort: 'Be the chef',
    featured: true,
    sortOrder: 1,
    tags: ['pizza'],
    variants: [
      { id: 'pizza-medium', name: 'Medium', price: 10000, active: true, isDefault: true },
      { id: 'pizza-large', name: 'Large', price: 15000, active: true },
    ],
    optionGroupIds: ['pizza_crust', 'pizza_sauce', 'pizza_cheese', 'pizza_toppings'],
    modifierGroups: getModifierGroupsByIds(['pizza_crust', 'pizza_sauce', 'pizza_cheese', 'pizza_toppings']),
  },
  {
    id: 'fruit-salad',
    name: 'FRUIT SALAD',
    description: 'A rainbow of fresh seasonal fruits cut at peak ripeness.',
    category: 'Fresh Fruits',
    categoryKey: 'fresh-fruits',
    categoryName: 'Fresh Fruits',
    basePrice: 2500,
    imageUrl: 'https://images.unsplash.com/photo-1564093497595-593b96d80180?auto=format&fit=crop&q=80&w=800',
    active: true,
    isAvailable: true,
    available: true,
    station: 'barista',
    prepStation: 'barista',
    fulfillmentMode: 'made_to_order',
    itemType: 'simple',
    tagline: 'Nature\'s candy bowl',
    descriptionShort: 'Nature\'s candy bowl',
    sortOrder: 1,
    tags: ['fruit', 'fresh'],
  },
  {
    id: 'fruit-platter',
    name: 'FRUIT PLATTER',
    description: 'Beautifully arranged fresh fruits that taste as good as they look.',
    category: 'Fresh Fruits',
    categoryKey: 'fresh-fruits',
    categoryName: 'Fresh Fruits',
    basePrice: 4000,
    imageUrl: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&q=80&w=800',
    active: true,
    isAvailable: true,
    available: true,
    station: 'barista',
    prepStation: 'barista',
    fulfillmentMode: 'made_to_order',
    itemType: 'simple',
    tagline: 'An edible work of art',
    descriptionShort: 'An edible work of art',
    sortOrder: 2,
    tags: ['fruit', 'fresh'],
  },
  {
    id: 'passion-juice',
    name: 'PASSION JUICE',
    description: 'Fresh passion fruit juice served chilled.',
    category: 'Fresh Juice',
    categoryKey: 'fresh-juice',
    categoryName: 'Fresh Juice',
    basePrice: 3000,
    imageUrl: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&q=80&w=800',
    active: true,
    isAvailable: true,
    available: true,
    station: 'barista',
    prepStation: 'barista',
    fulfillmentMode: 'made_to_order',
    itemType: 'simple',
    sortOrder: 1,
    tags: ['juice'],
  },
  {
    id: 'cafe-au-lait',
    name: 'CAFÉ AU LAIT',
    description: 'Coffee of the day with steamed milk.',
    category: 'Coffee & Espresso',
    categoryKey: 'coffee-espresso',
    categoryName: 'Coffee & Espresso',
    basePrice: 2500,
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=800',
    active: true,
    isAvailable: true,
    available: true,
    station: 'barista',
    prepStation: 'barista',
    fulfillmentMode: 'made_to_order',
    itemType: 'simple',
    tagline: 'French morning hug',
    featured: true,
    sortOrder: 1,
    tags: ['coffee'],
    reviews: [
      { user: 'Lorraine', rating: 5, comment: 'Perfect froth and temperature. A must try!', date: '14/03/24' },
    ],
    averageRating: 4.9,
  },
  {
    id: 'soda',
    name: 'SODA',
    description: 'Your favorite sparkling refreshment (300ml).',
    category: 'Beverages',
    categoryKey: 'beverages',
    categoryName: 'Beverages',
    basePrice: 1000,
    imageUrl: 'https://images.unsplash.com/photo-1543253687-c931c8e01820?auto=format&fit=crop&q=80&w=800',
    active: true,
    isAvailable: true,
    available: true,
    station: 'front_service',
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'simple',
    sortOrder: 1,
    tags: ['soft-drink'],
  },
  {
    id: 'espresso-martini',
    name: 'ESPRESSO MARTINI',
    description: 'Vodka blended with coffee liqueur and freshly pulled espresso.',
    category: 'Cocktails & Wines',
    categoryKey: 'cocktails-wines',
    categoryName: 'Cocktails & Wines',
    basePrice: 10000,
    imageUrl: 'https://images.unsplash.com/photo-1575023782549-62ca0d244b39?auto=format&fit=crop&q=80&w=800',
    active: true,
    isAvailable: true,
    available: true,
    station: 'barista',
    prepStation: 'barista',
    fulfillmentMode: 'made_to_order',
    itemType: 'simple',
    sortOrder: 1,
    tags: ['cocktail', 'alcohol'],
  },
  {
    id: 'red-wine',
    name: 'RED WINES',
    description: 'Available by the bottle or by the glass.',
    category: 'Cocktails & Wines',
    categoryKey: 'cocktails-wines',
    categoryName: 'Cocktails & Wines',
    basePrice: 3000,
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=800',
    active: true,
    isAvailable: true,
    available: true,
    station: 'front_service',
    prepStation: 'front',
    fulfillmentMode: 'ready_to_serve',
    itemType: 'variant',
    sortOrder: 2,
    tags: ['wine', 'alcohol'],
    variants: [
      { id: 'red-wine-glass', name: 'Glass', price: 3000, active: true, isDefault: true },
      { id: 'red-wine-bottle', name: 'Bottle', price: 30000, active: true },
    ],
  },
];

export const STATION_LABELS: Record<StationType, string> = {
  kitchen: 'Kitchen',
  barista: 'Barista',
  front_service: 'Front Service',
  bakery: 'Bakery',
  bar: 'Bar',
  coffee: 'Coffee',
};
